(function(){
"use strict";
const c=globalThis.DIAGNOSTIC_CONFIG, qs=c.sections.flatMap(s=>s.questions), form=document.querySelector("#diagnostic-form"), box=document.querySelector("#questionnaire"), count=document.querySelector("#answered-count"), bar=document.querySelector("#progress-bar"), report=document.querySelector("#report"), content=document.querySelector("#report-content"), nameInput=document.querySelector("#business-name");
const getOpt=(q,v)=>q.options.find(o=>o.value===v);
box.innerHTML=c.sections.map((s,i)=>'<section class="question-section"><div class="section-heading"><span>'+String(i+1).padStart(2,"0")+'</span><div><p class="eyebrow">Área de revisión</p><h2>'+s.title+'</h2><p>'+s.description+'</p></div></div><div class="question-grid">'+s.questions.map(q=>'<fieldset class="question-card" data-q="'+q.id+'"><legend><span>'+q.number+'</span>'+q.text+'</legend>'+q.options.map(o=>'<label class="option-row"><input type="radio" name="'+q.id+'" value="'+o.value+'"><span class="radio-mark"></span><span>'+o.label+'</span></label>').join("")+'<p class="question-error" hidden>Selecciona una respuesta.</p></fieldset>').join("")+'</div></section>').join("");
function answers(){return Object.fromEntries(qs.map(q=>[q.id,form.elements[q.id]?.value||""]));}
function progress(){const n=Object.values(answers()).filter(Boolean).length;count.textContent=n;bar.style.width=(n/15*100)+"%";}
function calculate(a){const areas=Object.keys(c.categories),scores=Object.fromEntries(areas.map(x=>[x,0])),severe=Object.fromEntries(areas.map(x=>[x,0])),concern=a.q3_mainConcern;scores[concern]++;qs.filter(q=>q.category).forEach(q=>{const s=getOpt(q,a[q.id]).score;scores[q.category]+=s;if(s===3)severe[q.category]++;});const order=c.tieBreakOrder;const ranked=areas.sort((x,y)=>scores[y]-scores[x]||(x===concern?-1:y===concern?1:0)||severe[y]-severe[x]||order.indexOf(x)-order.indexOf(y));return{scores,ranked,primary:ranked[0]};}
function render(r,business){const cat=c.categories[r.primary],score=r.scores[r.primary],priority=score>=5?"Alta":score>=3?"Media":"Baja";document.querySelector("#report-business-name").textContent=business;document.querySelector("#report-date").textContent=new Date().toLocaleDateString("es-MX",{dateStyle:"long"});content.innerHTML='<div class="report-overview"><div class="problem-highlight"><span>Problema principal</span><strong>'+cat.label+'</strong><small>'+score+' / 7 puntos</small></div><div class="priority-highlight priority-'+priority.toLowerCase()+'"><span>Prioridad</span><strong>'+priority+'</strong></div></div><div class="score-grid">'+Object.entries(r.scores).map(([a,s])=>'<div><span>'+c.categories[a].label+'</span><strong>'+s+'/7</strong></div>').join("")+'</div><article class="next-step"><span>Tus tres áreas prioritarias</span><h3>'+r.ranked.slice(0,3).map((a,i)=>(i+1)+'. '+c.categories[a].label+' ('+r.scores[a]+'/7)').join(" · ")+'</h3></article><div class="report-card"><span class="report-number">01</span><div><h3>Posibles causas</h3><ul>'+Object.values(cat.causeRules).flat().map(x=>'<li>'+x+'</li>').join("")+'</ul></div></div><div class="report-card"><span class="report-number">02</span><div><h3>Indicadores recomendados</h3><ul>'+cat.kpis.map(x=>'<li><strong>'+x[0]+':</strong> '+x[1]+'</li>').join("")+'</ul></div></div><div class="report-card"><span class="report-number">03</span><div><h3>Acciones inmediatas</h3><ul>'+cat.quickActions.map(x=>'<li>'+x+'</li>').join("")+'</ul></div></div><article class="next-step"><span>Siguiente paso</span><h3>'+cat.nextStep+'</h3></article><p class="disclaimer">'+c.disclaimer+'</p>';report.hidden=false;report.scrollIntoView({behavior:"smooth"};document.querySelector("#download-json-button").onclick=()=>{const data={fecha:new Date().toISOString(),negocio:business,respuestas:a,puntajes:r.scores,prioridades:r.ranked.slice(0,3)};const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const l=document.createElement("a");l.href=u;l.download="diagnostico-operativo.json";l.click();URL.revokeObjectURL(u);};}
form.addEventListener("change",progress);form.addEventListener("submit",e=>{e.preventDefault();const a=answers();let ok=true;qs.forEach(q=>{const f=document.querySelector('[data-q="'+q.id+'"]'),bad=!a[q.id];f.querySelector(".question-error").hidden=!bad;f.classList.toggle("question-invalid",bad);if(bad)ok=false;});const noName=!nameInput.value.trim();document.querySelector("#business-name-error").hidden=!noName;if(noName)ok=false;document.querySelector("#form-error").hidden=ok;if(ok)render(calculate(a),nameInput.value.trim());});document.querySelector("#reset-button").onclick=()=>{form.reset();report.hidden=true;progress();};progress();
})();